### ISSUE TITLE
'QRGenerator()' has protected access in 'tech.zeroed.libgdxqr.QRGenerator'

### ISSUE THREAD

**Issue by Fanom2813** [zeroed-tech/LibGDX-QR#2]
good evening, i am not able to instantiate `QRGenerator()` due to the above error

**Comment by zeroed-tech** [comment]
Hey @Fanom2813 ,
Looks like the documentation on this is out of date. What you want is `QRGenerator generator = QRCode.CreateGenerator();`
I'm sure there was a good reason I changed it to that but I can't remember why
Checkout https://github.com/zeroed-tech/LibGDX-QR-Demo/blob/63a506f9bbdd8962f756a67adcf924b4fb9e4ef1/core/src/tech/zeroed/libgdxqrdemo/GenerateTab.java#L282 for a working implementation
