### ISSUE TITLE
Rendering TextureRegion in ImageView 

### ISSUE THREAD

**Issue by Fanom2813** [zeroed-tech/LibGDX-QR#3]
Good Moring, finally i was able to implement `QRGenerator ` , the next step is to display it , is there a wat i can display the QR code in ImageView or i have to use `VisUI` like in the example ?

**Comment by zeroed-tech** [comment]
`generator.generate()` returns a TextureRegion so you should be able to use it with just about anything, you may need to wrap it in something to turn it into a Drawable or a Sprite depending on how you want to draw it

**Comment by Fanom2813** [comment]
kindly , share an example on how to get a `Drawable `or `Bitmap`?

**Comment by zeroed-tech** [comment]
I don't have an environment setup to test this ATM but if you google using a texture as a Drawable you should be able to find some help
